# /.github/workflows/ci.yaml
# GitHub actions workflow

name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup PNPM 6
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.1
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'
      - name: Check for lint/formatting errors
        run: |
          pnpm install
          pnpm lint
  test:
    name: Test
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x, 17.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup PNPM 6
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.1
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'
      - name: Run library tests
        run: |
          pnpm install
          pnpm test
  publish:
    name: Publish
    needs: [lint, test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup PNPM 6
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.1
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Publish package to NPM
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build package to upload to GitHub releases
        run: |
          npm pack
          mv typescript-template-*.tgz typescript-template.tgz
      - name: Create a Github release
        uses: softprops/action-gh-release@v1
        with:
          files: typescript-template.tgz
          body:
            You can view the changelog
            [here](https://github.com/gamemaker1/typescript-template/blob/master/changelog.md).
